# Generated by Django 5.2.17 on 2026-08-13 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('vocabulary', '0003_add_b1_cefr_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='selected_movies',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='user',
        ),
        migrations.CreateModel(
            name='UserWordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='new', max_length=10)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_statuses', to=settings.AUTH_USER_MODEL)),
                ('vocabulary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='vocabulary.vocabularyitem')),
            ],
            options={
                'verbose_name_plural': 'user word statuses',
                'ordering': ('status', 'vocabulary_item__word_or_phrase', 'pk'),
            },
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
        migrations.AddIndex(
            model_name='userwordstatus',
            index=models.Index(fields=['user', 'status'], name='word_status_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordstatus',
            index=models.Index(fields=['user', 'last_tested_at'], name='word_status_user_tested_idx'),
        ),
        migrations.AddConstraint(
            model_name='userwordstatus',
            constraint=models.UniqueConstraint(fields=('user', 'vocabulary_item'), name='unique_user_vocabulary_status'),
        ),
    ]
