# Generated by Django 5.2.17 on 2026-08-14 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_quizsession_questions_and_more'),
        ('vocabulary', '0003_add_b1_cefr_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordstatus',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='userwordstatus',
            index=models.Index(fields=['user', 'is_saved'], name='word_status_user_saved_idx'),
        ),
    ]
