MAX_GENERATION_ITEMS = 100
MIN_GENERATION_CANDIDATE_SURPLUS = 3
MAX_GENERATION_CANDIDATE_SURPLUS = 15
GENERATION_CANDIDATE_SURPLUS_RATIO = 0.20
MAX_GENERATION_CANDIDATES = MAX_GENERATION_ITEMS + MAX_GENERATION_CANDIDATE_SURPLUS
