# Generated by Django 5.x for Filmocabulary.

import django.db.models.deletion
from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_or_phrase", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("phrasal_verb", "Phrasal verb"),
                            ("idiom", "Idiom"),
                            ("collocation", "Collocation"),
                            ("noun", "Noun"),
                            ("adjective", "Adjective"),
                            ("verb", "Verb"),
                            ("adverb", "Adverb"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "cefr_level",
                    models.CharField(
                        choices=[("B2", "B2"), ("C1", "C1"), ("C2", "C2")],
                        max_length=2,
                    ),
                ),
                ("definition_en", models.TextField()),
                ("translation_tr", models.CharField(max_length=255)),
                ("example_sentence", models.TextField()),
                ("blank_sentence", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary_items",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "ordering": ("cefr_level", "word_or_phrase", "pk"),
                "indexes": [
                    models.Index(
                        fields=["movie", "cefr_level"],
                        name="vocab_movie_cefr_idx",
                    ),
                    models.Index(
                        fields=["movie", "type"],
                        name="vocab_movie_type_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        Lower("word_or_phrase"),
                        models.F("movie"),
                        name="vocab_unique_movie_term_ci",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cefr_level__in", ("B2", "C1", "C2"))),
                        name="vocab_valid_cefr",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type__in",
                                (
                                    "phrasal_verb",
                                    "idiom",
                                    "collocation",
                                    "noun",
                                    "adjective",
                                    "verb",
                                    "adverb",
                                    "other",
                                ),
                            )
                        ),
                        name="vocab_valid_type",
                    ),
                ],
            },
        ),
    ]

