# Generated by Django 5.x for Filmocabulary.
import django.core.validators
import django.db.models.deletion
import movies.models
from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1888),
                            django.core.validators.MaxValueValidator(movies.models.current_year),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "title"),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="movie_user_created_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        Lower("title"),
                        models.F("user"),
                        models.F("release_year"),
                        name="movie_user_title_year_ci_uniq",
                    ),
                    models.UniqueConstraint(
                        Lower("title"),
                        models.F("user"),
                        condition=models.Q(release_year__isnull=True),
                        name="movie_user_title_null_ci_uniq",
                    ),
                ],
            },
        )
    ]
